### PR TITLE
Swap container-interop for PSR-11

### LINKED ISSUE #6: Comply with PSR-11
Deprecate [container-interop](https://github.com/container-interop/container-interop) in favor of [PSR-11](https://www.php-fig.org/psr/psr-11/)

### PR DESCRIPTION
**Pull request by lhsazevedo**
Fixes #6.

### CODE REVIEW

**Comment by jeremeamia** [comment]
Should this require a major version bump?

**Comment by lhsazevedo** [comment]
container-interop's ContainerInterface now extends PSR-11 one so this should be a smooth transition.

**Comment by dlundgren** [comment]
This should be a major version bump, because the dependency will be changed.

**Comment by dlundgren** [comment]
It would be nice to get this merged and released, as I am currently using a copy of ProxyManager modified for PSR-11 compatibility.

**Comment by lhsazevedo** [comment]
@dlundgren Try my fork, ReStatic. [Github](https://github.com/lhsazevedo/restatic) - [Packagist](https://packagist.org/packages/lhsazevedo/restatic).

**Comment by dlundgren** [comment]
Thanks! I'll switch over my code to use your fork.

**Comment by jeremeamia** [comment]
@lhsazevedo @dlundgren Good plan. I don't really maintain this anymore, if you didn't notice. :-) Sorry.

**Comment by lhsazevedo** [comment]
@jeremeamia Do you mind archiving it? I'll make adding a link to the fork

**Comment by jeremeamia** [comment]
Here's the composer/packagist abandoned link. :-)

Screen Shot 2020-07-06 at 11 28 15 AM

**Pull request closed without merging**
